volumeclassname: zhitu-volstorage
volumepvname: zhitu-pv
volumepvpath: /nfsdata/zhitu/
# volumeserver: 172.31.15.33
volumeserver: 192.168.1.90
volumepvspace: 1Gi
volumename: www-web  # 不能随意修改
volumeinit: "true"
volumenum:
- num: "0"
- num: "1"
- num: "2"
# 总结点数，最后一个节点索引，如：4个节点，最后一个索引是3
lastnodeindex: 2
image: registry.elensdata.com/elensai/zhidatabase:v5

mysqlimage: registry.elensdata.com/elensai/mysql:5.7
mysqlvolumepvpath: /nfsdata/zhitu/mysql
mysqlrootpasswd: 123456
mysqlvolumespace: 1Gi

browser_ip: 192.168.1.243

