apiVersion: v1
kind: Service
metadata:
  name: zhitu-svc
  labels:
    dep: zhitu-svc
spec:
  type: NodePort
  ports:
    - port: 8370
      targetPort: zhice-port
      nodePort: 30010
      protocol: TCP
  selector:
    app: zhitu-app

