apiVersion: v1
kind: Service
metadata:
  name: zhitu-svc
  labels:
    dep: zhitu-svc
spec:
  type: NodePort
  ports:
    - name: app 
      port: 8370
      targetPort: zhitu-port
      nodePort: 58370
    - name: proxy
      port: 80
      targetPort: 80
      nodePort: 58378
  selector:
    app: zhitu-app

