apiVersion: v1
kind: ConfigMap
metadata:
  name: app-window-url
  namespace: elens-zhitu
data:
  app-window-url: |-
    var API_URL = {
      BASE_URL: "/api",
      ENV_DATASET_URL: "192.168.1.243:53888"
    }
  