apiVersion: v1
kind: Service
metadata:
  name: zhitu-es-svc
  labels:
    dep: zhitu-es-svc
spec:
  type: NodePort
  ports:
  - name: p-9200
    port: 9200
    targetPort: zhitu-es-92
  - name: p-9300
    port: 9300
    targetPort: zhitu-es-93
  selector:
    app: zhitu-es

