apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zhitu-es
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zhitu-es
    spec:
      containers:
      - name: pod-zhitu
        image: "registry.elensdata.com/elensai/es-5.1.1:zhicev6"
        imagePullPolicy: IfNotPresent
        # securityContext:
        #   runAsUser: 1000
        command: ["/bin/bash"]
        ports:
        - name: zhitu-es-92
          containerPort: 9200
        - name: zhitu-es-93
          containerPort: 9300
        volumeMounts:
        - name: es-yml-config
          mountPath: /user/apps/es-5.1.1/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: es-jvm-config
          mountPath: /user/apps/es-5.1.1/config/jvm.options
          subPath: jvm.options 
      volumes:
      - name: es-yml-config
        configMap:
          name: es-yml-config
          items:
          - key: es-yml-config
            path: elasticsearch.yml
      - name: es-jvm-config
        configMap:
          name: es-jvm-config
          items:
          - key: es-jvm-config
            path: jvm.options
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "test02"
        effect: "PreferNoSchedule"
