apiVersion: v1
kind: Pod
metadata:
  name: "init"
  labels:
    app: init
spec:
  restartPolicy: OnFailure
  containers:
  - name: init
    image: {{ .Values.image }}
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash", "-c", "sh /user/init.sh"]
    volumeMounts:
    - name: sh
      mountPath: /user/init.sh
      subPath: init.sh
  volumes:
  - name: sh
    configMap:
      name: initpsh
      items:
      - key: initpsh-config
        path: init.sh