apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: elens-zhitu
data:
  server-config: |-
    <?xml version="1.0"?>
    <config>
      <!--本地所需配置-->
      <OOZIE_CLIENT>http://web-0.ha-svc.elens-zhitu.svc.cluster.local:11000/oozie</OOZIE_CLIENT>
      <NAME_NODE>hdfs://web-0.ha-svc.elens-zhitu.svc.cluster.local:8020</NAME_NODE>
      <YARN_ADDRESS>http://web-1.ha-svc.elens-zhitu.svc.cluster.local:8088</YARN_ADDRESS>
      <YARN_LOGSADDRESS>web-0.ha-svc.elens-zhitu.svc.cluster.local:8042,web-1.ha-svc.elens-zhitu.svc.cluster.local:8042,web-2.ha-svc.elens-zhitu.svc.cluster.local:8042</YARN_LOGSADDRESS>
      <JOB_TRACKER>web-1.ha-svc.elens-zhitu.svc.cluster.local:8032</JOB_TRACKER>
      <HOSTNAME_CON>true</HOSTNAME_CON>
      <QUEUE_NAME>default</QUEUE_NAME>
      <APP_WORKSPACE>/EML/oozie</APP_WORKSPACE>
      <DRAFT_PATH>/EML/draft</DRAFT_PATH>
      <DATASET_PATH>/EML/lensData</DATASET_PATH>
      <DOWNLOAD_PATH>src/main/webapp/dowload/</DOWNLOAD_PATH>
      <MODULE_PATH>/EML/Modules</MODULE_PATH>
      <PROGRAMS_PATH>/EML/Programs</PROGRAMS_PATH>
      <DB_HOST>mysql-svc</DB_HOST>
      <DB_PORT>3306</DB_PORT>
      <DB_NAME>lens_dataprocess_plat</DB_NAME>
      <DB_USER>root</DB_USER>
      <DB_PASSWORD>123456</DB_PASSWORD>
      <DB_TIMEOUT>100</DB_TIMEOUT>
      <MAIL_HOST>mail.software.ict.ac.cn</MAIL_HOST>
      <MAIL_USERNAME>bda@software.ict.ac.cn</MAIL_USERNAME>
      <MAIL_PASSWORD>bda@ict</MAIL_PASSWORD>
      <TENSORFLOW_CLUSTER>elens-server2, elens-server3, elens-server5</TENSORFLOW_CLUSTER>
      <TENSORFLOW_MASTER>elens-server2</TENSORFLOW_MASTER>
      <TENSORFLOW_USER>root</TENSORFLOW_USER>

      <!--war 218包所需配置-->
      <!--<OOZIE_CLIENT>http://172.18.0.3:11000/oozie</OOZIE_CLIENT>-->
      <!--<NAME_NODE>hdfs://172.18.0.3:9000</NAME_NODE>-->
      <!--<YARN_ADDRESS>http://172.18.0.3:8088</YARN_ADDRESS>-->
      <!--<YARN_LOGSADDRESS>hadoop-master:8042,hadoop-slave1:8042,hadoop-slave2:8042</YARN_LOGSADDRESS>-->
      <!--<JOB_TRACKER>172.18.0.3:8032</JOB_TRACKER>-->
      <!--<HOSTNAME_CON>true</HOSTNAME_CON>-->
      <!--<QUEUE_NAME>default</QUEUE_NAME>-->
      <!--<APP_WORKSPACE>/EML/oozie</APP_WORKSPACE>-->
      <!--<DRAFT_PATH>/EML/draft</DRAFT_PATH>-->
      <!--<DATASET_PATH>/EML/Data</DATASET_PATH>-->
      <!--<MODULE_PATH>/EML/Modules</MODULE_PATH>-->
      <!--<DB_HOST>172.18.0.2</DB_HOST>-->
      <!--<DB_PORT>3306</DB_PORT>-->
      <!--<DB_NAME>lens_dataprocess_plat</DB_NAME>-->
      <!--<DB_USER>root</DB_USER>-->
      <!--<DB_PASSWORD>111111</DB_PASSWORD>-->
      <!--<DB_TIMEOUT>100</DB_TIMEOUT>-->
      <!--<MAIL_HOST>mail.software.ict.ac.cn</MAIL_HOST>-->
      <!--<MAIL_USERNAME>bda@software.ict.ac.cn</MAIL_USERNAME>-->
      <!--<MAIL_PASSWORD>bda@ict</MAIL_PASSWORD>-->
      <!--<TENSORFLOW_CLUSTER>hadoop-master, hadoop-slave1, hadoop-slave2</TENSORFLOW_CLUSTER>-->
      <!--<TENSORFLOW_MASTER>hadoop-master</TENSORFLOW_MASTER>-->
      <!--<TENSORFLOW_USER>root</TENSORFLOW_USER>-->

    </config>