apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zhitu-javaapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zhitu-javaapi
    spec:
      containers:
      - name: pod-zhitu
        image: "registry.elensdata.com/elensai/javaapp:zhicev1"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /user/apps/tomcat/webapps/lensData/application.properties
          name: application-properties-v
          subPath: application.properties
        - name: server-config
          mountPath: /user/apps/tomcat/webapps/lensData/server-config.xml
          subPath: server-config.xml
        ports:
        - name: javaport
          containerPort: 8080
      volumes:
      - name: application-properties-v
        configMap:
          name: application-properties-config
          items: 
          - key: application-properties
            path: application.properties
      - name: server-config
        configMap:
          name: server-config
          items:
          - key: server-config
            path: server-config.xml

      tolerations:
      - key: "key"
        operator: "Equal"
        value: "test02"
        effect: "PreferNoSchedule"
          
