apiVersion: v1
kind: Service
metadata:
  name: zhitu-javaapi-svc
  labels:
    dep: zhitu-javaapi-svc
spec:
  type: NodePort
  ports:
  - name: p-8080
    port: 8080
    nodePort: 53888
  selector:
    app: zhitu-javaapi

