apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zhitu-logstash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zhitu-logstash
    spec:
      nodeSelector:
        kubernetes.io/hostname: rancher-test-01
      containers:
        - name: pod-logstash
          image: "registry.elensdata.com/elensai/logstash5.1.1:zhicev4"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /user/apps/logstash/config/logstash.conf
            name: logstash-c
            subPath: logstash.conf
          
      volumes:
      - name: logstash-c
        configMap:
          name: logstash-config
          items:
          - key: logstash-config
            path: logstash.conf