apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zhitu-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zhitu-redis
    spec:
      nodeSelector:
        kubernetes.io/hostname: rancher-test-01
      containers:
        - name: pod-redis
          image: "registry.elensdata.com/elensai/redis:5.0.4"
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis-port
              containerPort: 6379
              