apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zhitu-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zhitu-redis
    spec:
      containers:
        - name: pod-redis
          image: {{ .Values.redisimage }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis-port
              containerPort: 6379
      tolerations:
        - key: "key"
          operator: "Equal"
          value: "test02"
          effect: "PreferNoSchedule"
              