{{- $classname := .Values.volumeclassname}}
{{- range .Values.volumenum }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ $classname }}-{{ .num }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
{{- end }}

---

{{- $volname := .Values.volumename}}
{{- $pvname := .Values.volumepvname}}
{{- $pvspace := .Values.volumepvspace}}
{{- $pvpath := .Values.volumepvpath}}
{{- $volserver := .Values.volumeserver}}
{{- range .Values.volumenum }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $pvname }}{{ .num }}
spec:
  capacity:
    storage: {{ $pvspace }}
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ $classname }}-{{ .num }}
  nfs:
    path: {{ $pvpath }}{{ $volname }}-{{ .num }}
    server: {{ $volserver }}
---
{{- end }}

---

{{- range .Values.volumenum }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $volname }}-{{ .num }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ $pvspace }}
  storageClassName: {{ $classname }}-{{ .num }}
---
{{- end }}

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: init-vl-s
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: init-vl-pv
spec:
  capacity:
    storage: 10M
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: init-vl-s
  nfs: 
    path: /nfsdata/zhitu/init
    server: {{ .Values.volumeserver }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: init-vl-c
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10M
  storageClassName: init-vl-s

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: es-vl-s
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-vl-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: es-vl-s
  nfs: 
    path: /nfsdata/zhitu/esdata
    server: {{ .Values.volumeserver }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-vl-c
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: es-vl-s
